### ISSUE TITLE
Hi,nice image but have one question

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [bradbeck/nexus-https#1]
The container does not run.

The error message is : Keystore was tampered with, or password was incorrect

Where can I configure nexus to use  the password that I used in my keystore ??

Regards,

Hans Nieuwenhuis

**Comment by bradbeck** [comment]
As it stands right now you'd have to modify the `jetty-https.xml` inside the docker image. It's currently configured to expect `password` for the passwords.

**Comment by arellano-gustavo** [comment]
Hey, @jhmnieuwenhuis late answer, but, you can run "normally" the image and then, just do this:
`docker inspect nexus | grep PRIVATE_KEY_PASSWORD`

and you will se this:
`PRIVATE_KEY_PASSWORD=password`
